## Importing the libraries and data

In [84]:
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
import scipy
from numpy import array
from numpy import vstack
from numpy import dstack
from pandas import read_csv
from pandas import DataFrame
from numpy import unique
from matplotlib import pyplot
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from keras.layers import Conv1D, Conv2D, Dense, BatchNormalization, Flatten, MaxPooling1D, LSTM
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

In [86]:
path = r'C:\Users\asicz\OneDrive\Dokumenty\CareerFoundry_Data_Analyst_Course\Machine Learning with Python\Data Sets\Unsupervised'

In [88]:
df = pd.read_csv(os.path.join(path, 'Dataset-weather-prediction-dataset-processed.csv'))
df_test = pd.read_csv(os.path.join(path,'Dataset-Answers-Weather_Prediction_Pleasant_Weather.csv'))

In [89]:
df.head()

,DATE,MONTH,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,19600101,1,7,2.1,0.85,1.018,0.32,0.09,0,0.7,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,19600102,1,6,2.1,0.84,1.018,0.36,1.05,0,1.1,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,19600103,1,8,2.1,0.90,1.018,0.18,0.30,0,0.0,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,19600104,1,3,2.1,0.92,1.018,0.58,0.00,0,4.1,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,19600105,1,6,2.1,0.95,1.018,0.65,0.14,0,5.4,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4

In [92]:
df_test.head()

,DATE,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,19600101,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,19600102,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,19600103,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,19600104,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,19600105,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## Prepare the data

In [95]:
# Drop the month and date columns
df = df.drop(columns=['MONTH', 'DATE'], errors='ignore')
df_test = df_test.drop(columns=['DATE'], errors='ignore')

In [97]:
df

,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,2.1,0.85,1.0180,0.32,0.09,0,0.7,6.5,0.8,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,6,2.1,0.84,1.0180,0.36,1.05,0,1.1,6.1,3.3,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,8,2.1,0.90,1.0180,0.18,0.30,0,0.0,8.5,5.1,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,3,2.1,0.92,1.0180,0.58,0.00,0,4.1,6.3,3.8,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,6,2.1,0.95,1.0180,0.65,0.14,0,5.4,3.0,-0.7,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,1,2.1,0.79,1.0248,1.34,0.22,0,7.7,15.9,11.4,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22946,6,2.1,0.77,1.0244,1.34,0.22,0,5.4,16.7,14.3,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22947,4,2.1,0.76,1.0227,1.34,0.22,0,6.1,16.7,13.1,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22948,5,2.1,0.80,1.0212,1.34,0.22,0,5.8,15.4,11.6,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22949,5,2.1,0.84,1.0193,1.34,0.22,0,3.2,13.5,9.9,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5

In [99]:
df_test

,BASEL_pleasant_weather,BELGRADE_pleasant_weather,BUDAPEST_pleasant_weather,DEBILT_pleasant_weather,DUSSELDORF_pleasant_weather,HEATHROW_pleasant_weather,KASSEL_pleasant_weather,LJUBLJANA_pleasant_weather,MAASTRICHT_pleasant_weather,MADRID_pleasant_weather,MUNCHENB_pleasant_weather,OSLO_pleasant_weather,SONNBLICK_pleasant_weather,STOCKHOLM_pleasant_weather,VALENTIA_pleasant_weather
0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22946,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22947,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22948,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22949,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [101]:
# List of prefixes you want to remove (from previous exercises)
prefixes_to_remove = ['GDANSK', 'ROMA', 'TOURS']

# Filter out columns that start with any of the missing prefixes
df= df[[col for col in df.columns if not any(col.startswith(prefix) for prefix in prefixes_to_remove)]]
df

,BASEL_cloud_cover,BASEL_wind_speed,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_snow_depth,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,...,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_snow_depth,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,2.1,0.85,1.0180,0.32,0.09,0,0.7,6.5,0.8,...,5,0.88,1.0003,0.45,0.34,0,4.7,8.5,6.0,10.9
1,6,2.1,0.84,1.0180,0.36,1.05,0,1.1,6.1,3.3,...,7,0.91,1.0007,0.25,0.84,0,0.7,8.9,5.6,12.1
2,8,2.1,0.90,1.0180,0.18,0.30,0,0.0,8.5,5.1,...,7,0.91,1.0096,0.17,0.08,0,0.1,10.5,8.1,12.9
3,3,2.1,0.92,1.0180,0.58,0.00,0,4.1,6.3,3.8,...,7,0.86,1.0184,0.13,0.98,0,0.0,7.4,7.3,10.6
4,6,2.1,0.95,1.0180,0.65,0.14,0,5.4,3.0,-0.7,...,3,0.80,1.0328,0.46,0.00,0,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,1,2.1,0.79,1.0248,1.34,0.22,0,7.7,15.9,11.4,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22946,6,2.1,0.77,1.0244,1.34,0.22,0,5.4,16.7,14.3,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22947,4,2.1,0.76,1.0227,1.34,0.22,0,6.1,16.7,13.1,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22948,5,2.1,0.80,1.0212,1.34,0.22,0,5.8,15.4,11.6,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5
22949,5,2.1,0.84,1.0193,1.34,0.22,0,3.2,13.5,9.9,...,5,0.82,1.0142,1.13,0.41,0,3.4,10.7,7.9,13.5

In [103]:
# Find all variables for all stations and check missing observations

obs_cols = [col for col in df.columns if '_' in col]
station_variable_pairs = [col.split('_', 1) for col in obs_cols]
presence_df = pd.DataFrame(station_variable_pairs, columns=['Station', 'Variable'])

presence_matrix = pd.crosstab(presence_df['Station'], presence_df['Variable'])
presence_matrix = presence_matrix.reset_index()

print(presence_matrix)

Variable     Station  cloud_cover  global_radiation  humidity  precipitation  \
0              BASEL            1                 1         1              1
1           BELGRADE            1                 1         1              1
2           BUDAPEST            1                 1         1              1
3             DEBILT            1                 1         1              1
4         DUSSELDORF            1                 1         1              1
5           HEATHROW            1                 1         1              1
6             KASSEL            0                 1         1              1
7          LJUBLJANA            1                 1         1              1
8         MAASTRICHT            1                 1         1              1
9             MADRID            1                 1         1              1
10          MUNCHENB            1                 1         1              1
11              OSLO            1                 1         1              1
12         SONNBLICK            1                 1         1              1
13         STOCKHOLM            1                 1         0              1
14          VALENTIA            1                 1         1              1

Variable  pressure  snow_depth  sunshine  temp_max  temp_mean  temp_min  \
0                1           1         1         1          1         1
1                1           0         1         1          1         1
2                1           0         1         1          1         1
3                1           0         1         1          1         1
4                1           1         1         1          1         1
5                1           1         1         1          1         1
6                1           0         1         1          1         1
7                1           0         1         1          1         1
8                1           0         1         1          1         1
9                1           0         1         1          1         1
10               0           1         1         1          1         1
11               1           1         1         1          1         1
12               1           0         1         1          1         1
13               1           0         1         1          1         1
14               1           1         1         1          1         1

Variable  wind_speed
0                  1
1                  0
2                  0
3                  1
4                  1
5                  0
6                  1
7                  1
8                  1
9                  1
10                 0
11                 1
12                 1
13                 0
14                 0

In [105]:
# Remove snow_depth and wind_speed from the dataset as they are most often missing variables
df = df[[col for col in df.columns if not col.endswith(('snow_depth', 'wind_speed'))]]

In [107]:
df

,BASEL_cloud_cover,BASEL_humidity,BASEL_pressure,BASEL_global_radiation,BASEL_precipitation,BASEL_sunshine,BASEL_temp_mean,BASEL_temp_min,BASEL_temp_max,BELGRADE_cloud_cover,...,STOCKHOLM_temp_max,VALENTIA_cloud_cover,VALENTIA_humidity,VALENTIA_pressure,VALENTIA_global_radiation,VALENTIA_precipitation,VALENTIA_sunshine,VALENTIA_temp_mean,VALENTIA_temp_min,VALENTIA_temp_max
0,7,0.85,1.0180,0.32,0.09,0.7,6.5,0.8,10.9,1,...,4.9,5,0.88,1.0003,0.45,0.34,4.7,8.5,6.0,10.9
1,6,0.84,1.0180,0.36,1.05,1.1,6.1,3.3,10.1,6,...,5.0,7,0.91,1.0007,0.25,0.84,0.7,8.9,5.6,12.1
2,8,0.90,1.0180,0.18,0.30,0.0,8.5,5.1,9.9,6,...,4.1,7,0.91,1.0096,0.17,0.08,0.1,10.5,8.1,12.9
3,3,0.92,1.0180,0.58,0.00,4.1,6.3,3.8,10.6,8,...,2.3,7,0.86,1.0184,0.13,0.98,0.0,7.4,7.3,10.6
4,6,0.95,1.0180,0.65,0.14,5.4,3.0,-0.7,6.0,8,...,4.3,3,0.80,1.0328,0.46,0.00,5.7,5.7,3.0,8.4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,1,0.79,1.0248,1.34,0.22,7.7,15.9,11.4,21.4,2,...,14.2,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22946,6,0.77,1.0244,1.34,0.22,5.4,16.7,14.3,21.9,0,...,14.3,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22947,4,0.76,1.0227,1.34,0.22,6.1,16.7,13.1,22.4,2,...,14.4,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22948,5,0.80,1.0212,1.34,0.22,5.8,15.4,11.6,21.1,1,...,12.4,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5
22949,5,0.84,1.0193,1.34,0.22,3.2,13.5,9.9,19.2,4,...,12.6,5,0.82,1.0142,1.13,0.41,3.4,10.7,7.9,13.5

In [109]:
# Replace the remaining missing variables
# Define stations and parameters
stations = sorted(set(col.split('_')[0] for col in df.columns if '_' in col))

print(f"Detected {len(stations)} stations:")
for station in stations:
    print(station)

parameters = sorted(set(col.split('_', 1)[1] for col in df.columns if '_' in col))

print(f"Detected {len(parameters)} parameters:")
for param in parameters:
    print(param)

Detected 15 stations:
BASEL
BELGRADE
BUDAPEST
DEBILT
DUSSELDORF
HEATHROW
KASSEL
LJUBLJANA
MAASTRICHT
MADRID
MUNCHENB
OSLO
SONNBLICK
STOCKHOLM
VALENTIA
Detected 9 parameters:
cloud_cover
global_radiation
humidity
precipitation
pressure
sunshine
temp_max
temp_mean
temp_min

In [111]:
# Fill missing columns
df['KASSEL_cloud_cover'] = df['LJUBLJANA_cloud_cover'].copy()
df['MUNCHENB_pressure'] = df['SONNBLICK_pressure'].copy()
df['STOCKHOLM_humidity'] = df['OSLO_humidity'].copy()

# Reorder columns
ordered_columns = [f"{station}_{param}" for station in stations for param in parameters if f"{station}_{param}" in df.columns]

# Reindex
df = df[ordered_columns]

# Check the columns order
for col in ordered_columns:
    print(col)

BASEL_cloud_cover
BASEL_global_radiation
BASEL_humidity
BASEL_precipitation
BASEL_pressure
BASEL_sunshine
BASEL_temp_max
BASEL_temp_mean
BASEL_temp_min
BELGRADE_cloud_cover
BELGRADE_global_radiation
BELGRADE_humidity
BELGRADE_precipitation
BELGRADE_pressure
BELGRADE_sunshine
BELGRADE_temp_max
BELGRADE_temp_mean
BELGRADE_temp_min
BUDAPEST_cloud_cover
BUDAPEST_global_radiation
BUDAPEST_humidity
BUDAPEST_precipitation
BUDAPEST_pressure
BUDAPEST_sunshine
BUDAPEST_temp_max
BUDAPEST_temp_mean
BUDAPEST_temp_min
DEBILT_cloud_cover
DEBILT_global_radiation
DEBILT_humidity
DEBILT_precipitation
DEBILT_pressure
DEBILT_sunshine
DEBILT_temp_max
DEBILT_temp_mean
DEBILT_temp_min
DUSSELDORF_cloud_cover
DUSSELDORF_global_radiation
DUSSELDORF_humidity
DUSSELDORF_precipitation
DUSSELDORF_pressure
DUSSELDORF_sunshine
DUSSELDORF_temp_max
DUSSELDORF_temp_mean
DUSSELDORF_temp_min
HEATHROW_cloud_cover
HEATHROW_global_radiation
HEATHROW_humidity
HEATHROW_precipitation
HEATHROW_pressure
HEATHROW_sunshine
HEATHROW_temp_max
HEATHROW_temp_mean
HEATHROW_temp_min
KASSEL_cloud_cover
KASSEL_global_radiation
KASSEL_humidity
KASSEL_precipitation
KASSEL_pressure
KASSEL_sunshine
KASSEL_temp_max
KASSEL_temp_mean
KASSEL_temp_min
LJUBLJANA_cloud_cover
LJUBLJANA_global_radiation
LJUBLJANA_humidity
LJUBLJANA_precipitation
LJUBLJANA_pressure
LJUBLJANA_sunshine
LJUBLJANA_temp_max
LJUBLJANA_temp_mean
LJUBLJANA_temp_min
MAASTRICHT_cloud_cover
MAASTRICHT_global_radiation
MAASTRICHT_humidity
MAASTRICHT_precipitation
MAASTRICHT_pressure
MAASTRICHT_sunshine
MAASTRICHT_temp_max
MAASTRICHT_temp_mean
MAASTRICHT_temp_min
MADRID_cloud_cover
MADRID_global_radiation
MADRID_humidity
MADRID_precipitation
MADRID_pressure
MADRID_sunshine
MADRID_temp_max
MADRID_temp_mean
MADRID_temp_min
MUNCHENB_cloud_cover
MUNCHENB_global_radiation
MUNCHENB_humidity
MUNCHENB_precipitation
MUNCHENB_pressure
MUNCHENB_sunshine
MUNCHENB_temp_max
MUNCHENB_temp_mean
MUNCHENB_temp_min
OSLO_cloud_cover
OSLO_global_radiation
OSLO_humidity
OSLO_precipitation
OSLO_pressure
OSLO_sunshine
OSLO_temp_max
OSLO_temp_mean
OSLO_temp_min
SONNBLICK_cloud_cover
SONNBLICK_global_radiation
SONNBLICK_humidity
SONNBLICK_precipitation
SONNBLICK_pressure
SONNBLICK_sunshine
SONNBLICK_temp_max
SONNBLICK_temp_mean
SONNBLICK_temp_min
STOCKHOLM_cloud_cover
STOCKHOLM_global_radiation
STOCKHOLM_humidity
STOCKHOLM_precipitation
STOCKHOLM_pressure
STOCKHOLM_sunshine
STOCKHOLM_temp_max
STOCKHOLM_temp_mean
STOCKHOLM_temp_min
VALENTIA_cloud_cover
VALENTIA_global_radiation
VALENTIA_humidity
VALENTIA_precipitation
VALENTIA_pressure
VALENTIA_sunshine
VALENTIA_temp_max
VALENTIA_temp_mean
VALENTIA_temp_min

C:\Users\asicz\AppData\Local\Temp\ipykernel_9700\3347510674.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['KASSEL_cloud_cover'] = df['LJUBLJANA_cloud_cover'].copy()
C:\Users\asicz\AppData\Local\Temp\ipykernel_9700\3347510674.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['MUNCHENB_pressure'] = df['SONNBLICK_pressure'].copy()
C:\Users\asicz\AppData\Local\Temp\ipykernel_9700\3347510674.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['STOCKHOLM_humidity'] = df['OSLO_humidity'].copy()

In [113]:
df

,BASEL_cloud_cover,BASEL_global_radiation,BASEL_humidity,BASEL_precipitation,BASEL_pressure,BASEL_sunshine,BASEL_temp_max,BASEL_temp_mean,BASEL_temp_min,BELGRADE_cloud_cover,...,STOCKHOLM_temp_min,VALENTIA_cloud_cover,VALENTIA_global_radiation,VALENTIA_humidity,VALENTIA_precipitation,VALENTIA_pressure,VALENTIA_sunshine,VALENTIA_temp_max,VALENTIA_temp_mean,VALENTIA_temp_min
0,7,0.32,0.85,0.09,1.0180,0.7,10.9,6.5,0.8,1,...,2.2,5,0.45,0.88,0.34,1.0003,4.7,10.9,8.5,6.0
1,6,0.36,0.84,1.05,1.0180,1.1,10.1,6.1,3.3,6,...,3.0,7,0.25,0.91,0.84,1.0007,0.7,12.1,8.9,5.6
2,8,0.18,0.90,0.30,1.0180,0.0,9.9,8.5,5.1,6,...,1.3,7,0.17,0.91,0.08,1.0096,0.1,12.9,10.5,8.1
3,3,0.58,0.92,0.00,1.0180,4.1,10.6,6.3,3.8,8,...,0.4,7,0.13,0.86,0.98,1.0184,0.0,10.6,7.4,7.3
4,6,0.65,0.95,0.14,1.0180,5.4,6.0,3.0,-0.7,8,...,0.8,3,0.46,0.80,0.00,1.0328,5.7,8.4,5.7,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22945,1,1.34,0.79,0.22,1.0248,7.7,21.4,15.9,11.4,2,...,8.2,5,1.13,0.82,0.41,1.0142,3.4,13.5,10.7,7.9
22946,6,1.34,0.77,0.22,1.0244,5.4,21.9,16.7,14.3,0,...,11.0,5,1.13,0.82,0.41,1.0142,3.4,13.5,10.7,7.9
22947,4,1.34,0.76,0.22,1.0227,6.1,22.4,16.7,13.1,2,...,12.1,5,1.13,0.82,0.41,1.0142,3.4,13.5,10.7,7.9
22948,5,1.34,0.80,0.22,1.0212,5.8,21.1,15.4,11.6,1,...,5.1,5,1.13,0.82,0.41,1.0142,3.4,13.5,10.7,7.9
22949,5,1.34,0.84,0.22,1.0193,3.2,19.2,13.5,9.9,4,...,5.0,5,1.13,0.82,0.41,1.0142,3.4,13.5,10.7,7.9

In [115]:
df.to_csv('Dataset-weather-prediction-dataset-processed_cleaned.csv', index=False)

## Deep learning preparation

In [117]:
# Define X and y
X = df
y = df_test

In [118]:
# Convert X and y to arrays
X = np.array(X)
y = np.array(y)

In [119]:
X

array([[ 7.  ,  0.32,  0.85, ..., 10.9 ,  8.5 ,  6.  ],
       [ 6.  ,  0.36,  0.84, ..., 12.1 ,  8.9 ,  5.6 ],
       [ 8.  ,  0.18,  0.9 , ..., 12.9 , 10.5 ,  8.1 ],
       ...,
       [ 4.  ,  1.34,  0.76, ..., 13.5 , 10.7 ,  7.9 ],
       [ 5.  ,  1.34,  0.8 , ..., 13.5 , 10.7 ,  7.9 ],
       [ 5.  ,  1.34,  0.84, ..., 13.5 , 10.7 ,  7.9 ]])

In [124]:
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [126]:
# Reshape X
X = X.reshape(-1,15,9)

In [128]:
X.shape

(22950, 15, 9)

In [130]:
y.shape

(22950, 15)

In [132]:
# Split the data to training and testing
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state = 42)

## Create model and run RNN

In [203]:
#Create a Keras model
epochs = 30
batch_size = 16
n_hidden = 16

timesteps = len(X_train[0])
input_dim = len(X_train[0][0])
n_classes = len(y_train[0])

model = Sequential()
model.add(Conv1D(n_hidden, kernel_size=3, activation='relu', input_shape=(timesteps, input_dim)))
model.add(MaxPooling1D(pool_size=2))
model.add(LSTM(n_hidden, input_shape=(timesteps, input_dim)))
model.add(Dropout(0.3))
model.add(Dense(n_classes, activation='softmax')) #Don't use relu here!

C:\Users\asicz\anaconda3\Lib\site-packages\keras\src\layers\convolutional\base_conv.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
C:\Users\asicz\anaconda3\Lib\site-packages\keras\src\layers\rnn\rnn.py:204: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [205]:
model.compile(loss='categorical_crossentropy',
              optimizer='rmsprop',
              metrics=['accuracy'])

In [207]:
model.fit(X_train,
          y_train,
          batch_size=batch_size,
          validation_data=(X_test, y_test),
          epochs=epochs)

Epoch 1/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 17s 10ms/step - accuracy: 0.1239 - loss: 9.7372 - val_accuracy: 0.2137 - val_loss: 8.8819
Epoch 2/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - accuracy: 0.1359 - loss: 9.5546 - val_accuracy: 0.2149 - val_loss: 9.0978
Epoch 3/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - accuracy: 0.1052 - loss: 9.7458 - val_accuracy: 0.0807 - val_loss: 9.5657
Epoch 4/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.1022 - loss: 10.3834 - val_accuracy: 0.0802 - val_loss: 10.0643
Epoch 5/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.0961 - loss: 10.8476 - val_accuracy: 0.0819 - val_loss: 10.3836
Epoch 6/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0865 - loss: 11.1659 - val_accuracy: 0.0807 - val_loss: 10.8262
Epoch 7/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.0846 - loss: 11.5976 - val_accuracy: 0.0819 - val_loss: 11.1696
Epoch 8/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.0799 - loss: 11.7319 - val_accuracy: 0.0833 - val_loss: 11.5174
Epoch 9/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.0827 - loss: 12.1716 - val_accuracy: 0.0826 - val_loss: 11.8908
Epoch 10/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0777 - loss: 12.6467 - val_accuracy: 0.0859 - val_loss: 12.2407
Epoch 11/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.0799 - loss: 12.6984 - val_accuracy: 0.0817 - val_loss: 12.4787
Epoch 12/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.0764 - loss: 13.0563 - val_accuracy: 0.0809 - val_loss: 12.8391
Epoch 13/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.0744 - loss: 13.5718 - val_accuracy: 0.0854 - val_loss: 13.1367
Epoch 14/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0747 - loss: 13.7932 - val_accuracy: 0.0809 - val_loss: 13.3619
Epoch 15/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.0688 - loss: 14.0912 - val_accuracy: 0.0802 - val_loss: 13.6054
Epoch 16/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 6s 6ms/step - accuracy: 0.0661 - loss: 14.3017 - val_accuracy: 0.0807 - val_loss: 13.8756
Epoch 17/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.0676 - loss: 14.9036 - val_accuracy: 0.0817 - val_loss: 14.0888
Epoch 18/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.0641 - loss: 15.0803 - val_accuracy: 0.0803 - val_loss: 14.3070
Epoch 19/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.0640 - loss: 15.1397 - val_accuracy: 0.0824 - val_loss: 14.6900
Epoch 20/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.0641 - loss: 15.4218 - val_accuracy: 0.0795 - val_loss: 14.9813
Epoch 21/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.0645 - loss: 15.7147 - val_accuracy: 0.0809 - val_loss: 15.2221
Epoch 22/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 6ms/step - accuracy: 0.0590 - loss: 15.9289 - val_accuracy: 0.0807 - val_loss: 15.4821
Epoch 23/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.0628 - loss: 16.3057 - val_accuracy: 0.0652 - val_loss: 15.7259
Epoch 24/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 6ms/step - accuracy: 0.0587 - loss: 16.5042 - val_accuracy: 0.0537 - val_loss: 16.0776
Epoch 25/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.0610 - loss: 16.6128 - val_accuracy: 0.0610 - val_loss: 16.2108
Epoch 26/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.0579 - loss: 17.2658 - val_accuracy: 0.0591 - val_loss: 16.4331
Epoch 27/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 7s 7ms/step - accuracy: 0.0525 - loss: 16.9316 - val_accuracy: 0.0789 - val_loss: 16.6426
Epoch 28/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 5ms/step - accuracy: 0.0546 - loss: 17.2565 - val_accuracy: 0.0568 - val_loss: 16.7860
Epoch 29/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 12s 6ms/step - accuracy: 0.0535 - loss: 17.6366 - val_accuracy: 0.0638 - val_loss: 17.0206
Epoch 30/30
1076/1076 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - accuracy: 0.0633 - loss: 18.1973 - val_accuracy: 0.0547 - val_loss: 17.2246

In [235]:
print(len(model.layers))

3

In [237]:
model.weights

[<KerasVariable shape=(9, 64), dtype=float32, path=sequential_4/lstm_3/lstm_cell/kernel>,
 <KerasVariable shape=(16, 64), dtype=float32, path=sequential_4/lstm_3/lstm_cell/recurrent_kernel>,
 <KerasVariable shape=(64,), dtype=float32, path=sequential_4/lstm_3/lstm_cell/bias>,
 <KerasVariable shape=(16, 15), dtype=float32, path=sequential_4/dense_3/kernel>,
 <KerasVariable shape=(15,), dtype=float32, path=sequential_4/dense_3/bias>]

In [185]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv1d_1 (Conv1D)               │ (None, 14, 16)         │           304 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pooling1d_1 (MaxPooling1D)  │ (None, 7, 16)          │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_4 (LSTM)                   │ (None, 16)             │         2,112 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_4 (Dropout)             │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 15)             │           255 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 8,015 (31.31 KB)

 Trainable params: 2,671 (10.43 KB)

 Non-trainable params: 0 (0.00 B)

 Optimizer params: 5,344 (20.88 KB)

## Evaluate the model

In [142]:
# Create the weather stations dictionary
stations = {
0: 'BASEL',
1: 'BELGRADE',
2: 'BUDAPEST',
3: 'DEBILT',
4: 'DUSSELDORF',
5: 'HEATHROW',
6: 'KASSEL',
7: 'LJUBLJANA',
8: 'MAASTRICHT',
9: 'MADRID',
10: 'MUNCHENB',
11: 'OSLO',
12: 'SONNBLICK',
13: 'STOCKHOLM',
14: 'VALENTIA'
}

In [209]:
# Create confusion matrix for the weather stations

def confusion_matrix(Y_true, Y_pred):
    Y_true = pd.Series([stations[y] for y in np.argmax(Y_true, axis=1)])
    Y_pred = pd.Series([stations[y] for y in np.argmax(Y_pred, axis=1)])

    return pd.crosstab(Y_true, Y_pred, rownames=['True'], colnames=['Pred'])

In [211]:
# Evaluate
print(confusion_matrix(y_test, model.predict(X_test)))

180/180 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step
Pred        BASEL  BELGRADE  BUDAPEST  MADRID
True
BASEL           1      2243         8    1430
BELGRADE        0        80        12    1000
BUDAPEST        1         6         1     206
DEBILT          0         0         0      82
DUSSELDORF      0         2         0      27
HEATHROW        0        12         0      70
KASSEL          0         0         0      11
LJUBLJANA       0         4         2      55
MAASTRICHT      0         5         0       4
MADRID          0       225         1     232
MUNCHENB        0         4         1       3
OSLO            0         0         1       4
STOCKHOLM       0         0         0       4
VALENTIA        0         1         0       0